language: python

python:
    - "2.7"

install:
    "pip install -r requerimientos.txt"

before_script:
    - autopep8 -ir *
    - flake8 --max-complexity=8 --exclude=*.txt,*.md,*

script:
    - cd tests/features
    - python TestEdad.py
    - coverage run --branch TestEdad.py
    - coverage report
    - cd ..
    - lettuce
